/**
*	Script que realiza la insercción de la auditoria de la tabla Mascotas.
*	Autor: Daniela Prado Chaparro
*	Fecha: 12-09-2021
*	Universidad El Bosque
*	Base de Datos 2
*	Taller 2
*/

DROP TABLE MASCOTAAUDITORIA;
/**
 * Creación de la tabla.
 */
CREATE TABLE MASCOTAAUDITORIA(
	codigoAuditoria SERIAL UNIQUE,
	codigoMascota VARCHAR(10) NOT NULL,
	documentoUsuario VARCHAR(15) NOT NULL,
	nombreUsuario VARCHAR(100) NOT NULL,
	nombreMascota VARCHAR(30) NOT NULL,
	edad INT NOT NULL,
	especie VARCHAR(30) NOT NULL,
	sexo VARCHAR(2) NOT NULL,
	tamano NUMERIC NOT NULL,
	peligroso BIT NOT NULL,
	foto VARCHAR(50) NOT NULL,
	activo BIT NOT NULL,
	accionAuditoria VARCHAR(15) NOT NULL,
	fechaAuditoria TIMESTAMP DEFAULT NOW() NOT NULL
);

/**
 * Función que ejecutara el trigger que sera disparado cuando se actualice o inserte un registro, la eliminación de datos
 * no esta permitida en la tabla.
 */
CREATE OR REPLACE FUNCTION fcnAuditoriaMascota()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
	AS
$$ DECLARE
	BEGIN
		
		IF(TG_OP = 'DELETE') THEN
			RAISE 'Accion no permitida';
		END IF;
	
		IF EXISTS(SELECT CODIGOMASCOTA FROM MASCOTA WHERE CODIGOMASCOTA = NEW.CODIGOMASCOTA AND TG_OP = 'INSERT') THEN
			INSERT INTO MASCOTAAUDITORIA
						(CODIGOMASCOTA, DOCUMENTOUSUARIO, NOMBREUSUARIO, NOMBREMASCOTA, EDAD, ESPECIE, SEXO, TAMANO, PELIGROSO, FOTO,
						ACTIVO, ACCIONAUDITORIA, FECHAAUDITORIA)
			SELECT 		MASCOTA.CODIGOMASCOTA, MASCOTA.DOCUMENTOUSUARIO, USUARIO.NOMBREUSUARIO, MASCOTA.NOMBREMASCOTA, MASCOTA.EDAD,
						MASCOTA.ESPECIE, MASCOTA.SEXO, MASCOTA.TAMANO, MASCOTA.PELIGROSO, MASCOTA.FOTO, MASCOTA.ACTIVO, TG_OP, NOW()
			FROM 		MASCOTA
			INNER JOIN 	USUARIO
			ON			MASCOTA.DOCUMENTOUSUARIO = USUARIO.DOCUMENTOUSUARIO
			WHERE 		MASCOTA.CODIGOMASCOTA = NEW.CODIGOMASCOTA;
			RETURN NEW;
		ELSEIF (TG_OP = 'UPDATE') THEN
			INSERT INTO MASCOTAAUDITORIA
						(CODIGOMASCOTA, DOCUMENTOUSUARIO, NOMBREUSUARIO, NOMBREMASCOTA, EDAD, ESPECIE, SEXO, TAMANO, PELIGROSO, FOTO,
						ACTIVO, ACCIONAUDITORIA, FECHAAUDITORIA)
			SELECT 		MASCOTA.CODIGOMASCOTA, OLD.DOCUMENTOUSUARIO, USUARIO.NOMBREUSUARIO, OLD.NOMBREMASCOTA, OLD.EDAD,
						OLD.ESPECIE, OLD.SEXO, OLD.TAMANO, OLD.PELIGROSO, OLD.FOTO, OLD.ACTIVO, TG_OP, NOW()
			FROM 		MASCOTA
			INNER JOIN 	USUARIO
			ON			MASCOTA.DOCUMENTOUSUARIO = USUARIO.DOCUMENTOUSUARIO
			WHERE 		MASCOTA.CODIGOMASCOTA = OLD.CODIGOMASCOTA;
			RETURN NEW;
		ELSE
			RAISE 'La mascota no existe.';			
		END IF;
	
	END;
$$;

/**
 * Creación del trigger.
 */
DROP TRIGGER IF EXISTS trgAuditoriaMascota ON Mascota;
CREATE TRIGGER trgAuditoriaMascota
	AFTER INSERT OR UPDATE OR DELETE ON Mascota
	FOR EACH ROW
	EXECUTE PROCEDURE fcnAuditoriaMascota();

/**
* Prueba del trigger
*/
INSERT INTO MASCOTA
		(CODIGOMASCOTA, DOCUMENTOUSUARIO, NOMBREMASCOTA, EDAD, ESPECIE, SEXO, TAMANO, PELIGROSO, FOTO, ACTIVO)
	VALUES
		('MAS004', '123456789', 'Mascota 3', 4, 'Perro', 'F', '98.5', '0', 'aqui va la ruta de la foto', '1');
		
UPDATE 	MASCOTA
SET		NOMBREMASCOTA = 'Firulais 3', EDAD = 3, SEXO = 'F', TAMANO = 85.7, PELIGROSO = '1'
WHERE 	CODIGOMASCOTA = 'MAS004';